let a = 5;
let b = 10;
console.log("a + b is ", a+b);
console.log("a * b is ", a*b);
console.log("a - b is ", a-b);
console.log("a / b is ", a/b);
console.log("a % b is ", a%b);
console.log("a ** b is ", a**b);
console.log("a ++ b is ", a ++);
console.log("a -- b is ", a --);